// <auto-generated />
namespace QuranEducation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_st_tut : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_st_tut));
        
        string IMigrationMetadata.Id
        {
            get { return "202012251420102_add_st_tut"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
