//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranEducation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuranRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuranRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuranEducation.QuranRes", typeof(QuranRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about me.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable.
        /// </summary>
        public static string Acceptable {
            get {
                return ResourceManager.GetString("Acceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptInst {
            get {
                return ResourceManager.GetString("AcceptInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account was temporary Locked out.
        /// </summary>
        public static string AccountWasLocked {
            get {
                return ResourceManager.GetString("AccountWasLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement File.
        /// </summary>
        public static string AchievementFile {
            get {
                return ResourceManager.GetString("AchievementFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Add or Edited Assignment .
        /// </summary>
        public static string AddAssMsg2 {
            get {
                return ResourceManager.GetString("AddAssMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor .
        /// </summary>
        public static string AddLecMsg1 {
            get {
                return ResourceManager.GetString("AddLecMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Added or edited New Lecture .
        /// </summary>
        public static string AddLecMsg2 {
            get {
                return ResourceManager.GetString("AddLecMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to Tutorial .
        /// </summary>
        public static string AddLecMsg3 {
            get {
                return ResourceManager.GetString("AddLecMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Forms.
        /// </summary>
        public static string AdministrativeForms {
            get {
                return ResourceManager.GetString("AdministrativeForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already Evaluate this instructor before.
        /// </summary>
        public static string Alreadyeval {
            get {
                return ResourceManager.GetString("Alreadyeval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher attends on time.
        /// </summary>
        public static string ArriveInATime {
            get {
                return ResourceManager.GetString("ArriveInATime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment-Homework Attachments.
        /// </summary>
        public static string AssAttach {
            get {
                return ResourceManager.GetString("AssAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Assignment-Homework Degree.
        /// </summary>
        public static string AssDegree {
            get {
                return ResourceManager.GetString("AssDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment-Homework Details.
        /// </summary>
        public static string AssDesc {
            get {
                return ResourceManager.GetString("AssDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment-homework End Date and time should be after start date and time.
        /// </summary>
        public static string assEndBeggerThanLecStart {
            get {
                return ResourceManager.GetString("assEndBeggerThanLecStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment-Homework End Date.
        /// </summary>
        public static string AssEndDate {
            get {
                return ResourceManager.GetString("AssEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment-Homework End Time.
        /// </summary>
        public static string AssEndTime {
            get {
                return ResourceManager.GetString("AssEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments and Homeworks List.
        /// </summary>
        public static string AssigmentList {
            get {
                return ResourceManager.GetString("AssigmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments and Homeworks.
        /// </summary>
        public static string AssigmentTitle {
            get {
                return ResourceManager.GetString("AssigmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment Solution.
        /// </summary>
        public static string AssSolution {
            get {
                return ResourceManager.GetString("AssSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments Soluations.
        /// </summary>
        public static string AssSolutions {
            get {
                return ResourceManager.GetString("AssSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment-Homework Start Date.
        /// </summary>
        public static string AssStDate {
            get {
                return ResourceManager.GetString("AssStDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment-Homework Start Time.
        /// </summary>
        public static string AssStTime {
            get {
                return ResourceManager.GetString("AssStTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment-homework start date and time should be after current date and time.
        /// </summary>
        public static string assTimeError {
            get {
                return ResourceManager.GetString("assTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment-Homework Title.
        /// </summary>
        public static string AssTitle {
            get {
                return ResourceManager.GetString("AssTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial not found for this Assignment.
        /// </summary>
        public static string AssTutNotFound {
            get {
                return ResourceManager.GetString("AssTutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment or Homework.
        /// </summary>
        public static string AssType {
            get {
                return ResourceManager.GetString("AssType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        public static string AsstypeTitle {
            get {
                return ResourceManager.GetString("AsstypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment deleted.
        /// </summary>
        public static string AttRemoved {
            get {
                return ResourceManager.GetString("AttRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured When try to delete this attachment.
        /// </summary>
        public static string AttRemoveError {
            get {
                return ResourceManager.GetString("AttRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Home.
        /// </summary>
        public static string BackBtn {
            get {
                return ResourceManager.GetString("BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string BackTut {
            get {
                return ResourceManager.GetString("BackTut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth of Date.
        /// </summary>
        public static string BOD {
            get {
                return ResourceManager.GetString("BOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select degree for this studen.
        /// </summary>
        public static string CertifyError {
            get {
                return ResourceManager.GetString("CertifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to find this user or old password was wrong !.
        /// </summary>
        public static string ChangePassFailed {
            get {
                return ResourceManager.GetString("ChangePassFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can change password later.
        /// </summary>
        public static string ChangePassLater {
            get {
                return ResourceManager.GetString("ChangePassLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change My Password.
        /// </summary>
        public static string ChangePassTextUrl {
            get {
                return ResourceManager.GetString("ChangePassTextUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid code.
        /// </summary>
        public static string codeNotValid {
            get {
                return ResourceManager.GetString("codeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords not matches.
        /// </summary>
        public static string ConfirmPassErrorText {
            get {
                return ResourceManager.GetString("ConfirmPassErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReEnter Password.
        /// </summary>
        public static string ConfirmPassText {
            get {
                return ResourceManager.GetString("ConfirmPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Assignment - Homework.
        /// </summary>
        public static string CreateAss {
            get {
                return ResourceManager.GetString("CreateAss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Lecture.
        /// </summary>
        public static string CreateLec {
            get {
                return ResourceManager.GetString("CreateLec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this attachment ?.
        /// </summary>
        public static string DeleteAttQues {
            get {
                return ResourceManager.GetString("DeleteAttQues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data in this table.
        /// </summary>
        public static string DtsEmptyTable {
            get {
                return ResourceManager.GetString("DtsEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string DtsFirst {
            get {
                return ResourceManager.GetString("DtsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show_START_ to_END_ from total _TOTAL_ record.
        /// </summary>
        public static string DtsInfo {
            get {
                return ResourceManager.GetString("DtsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shoing 0  to 0 from total 0 records.
        /// </summary>
        public static string DtsInfoEmpty {
            get {
                return ResourceManager.GetString("DtsInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ records).
        /// </summary>
        public static string DtsInfoFiltered {
            get {
                return ResourceManager.GetString("DtsInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string DtsLast {
            get {
                return ResourceManager.GetString("DtsLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show _MENU_ records.
        /// </summary>
        public static string DtsLengthMenu {
            get {
                return ResourceManager.GetString("DtsLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string DtsNext {
            get {
                return ResourceManager.GetString("DtsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string DtsPrevious {
            get {
                return ResourceManager.GetString("DtsPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string DtsSearch {
            get {
                return ResourceManager.GetString("DtsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending Sort: .
        /// </summary>
        public static string DtsSortAscending {
            get {
                return ResourceManager.GetString("DtsSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending Sort:.
        /// </summary>
        public static string DtsSortDescending {
            get {
                return ResourceManager.GetString("DtsSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no records to show.
        /// </summary>
        public static string DtsZeroRecords {
            get {
                return ResourceManager.GetString("DtsZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfileBtn {
            get {
                return ResourceManager.GetString("EditProfileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic year.
        /// </summary>
        public static string EduYear {
            get {
                return ResourceManager.GetString("EduYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is Already Taken by another person.
        /// </summary>
        public static string EmailAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in English Language.
        /// </summary>
        public static string EnName {
            get {
                return ResourceManager.GetString("EnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code we sent to your Email.
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter valid email this email not found.
        /// </summary>
        public static string EnterCorrectPhone {
            get {
                return ResourceManager.GetString("EnterCorrectPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please fix these errors.
        /// </summary>
        public static string ErrorSumTitle {
            get {
                return ResourceManager.GetString("ErrorSumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Reset Password.
        /// </summary>
        public static string ErrorWhileResetPass {
            get {
                return ResourceManager.GetString("ErrorWhileResetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Evaluation was send.
        /// </summary>
        public static string EvalSent {
            get {
                return ResourceManager.GetString("EvalSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate Student.
        /// </summary>
        public static string EvalStudent {
            get {
                return ResourceManager.GetString("EvalStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evaluated.
        /// </summary>
        public static string evaluated {
            get {
                return ResourceManager.GetString("evaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Notis.
        /// </summary>
        public static string FatherNoti {
            get {
                return ResourceManager.GetString("FatherNoti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileTitle {
            get {
                return ResourceManager.GetString("FileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher communicates with you well and kindly.
        /// </summary>
        public static string GoodCommunications {
            get {
                return ResourceManager.GetString("GoodCommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teaching method is appropriate .
        /// </summary>
        public static string GoodInStudy {
            get {
                return ResourceManager.GetString("GoodInStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher uses the board effectively.
        /// </summary>
        public static string GoodInUsingBoard {
            get {
                return ResourceManager.GetString("GoodInUsingBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hear the yeacher clearly.
        /// </summary>
        public static string GoodInVoice {
            get {
                return ResourceManager.GetString("GoodInVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homework.
        /// </summary>
        public static string HMtypeTitle {
            get {
                return ResourceManager.GetString("HMtypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string HomeIndexTitle {
            get {
                return ResourceManager.GetString("HomeIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome of you in Portal of Etkan.
        /// </summary>
        public static string HomeIndexWelcome {
            get {
                return ResourceManager.GetString("HomeIndexWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival at.
        /// </summary>
        public static string InboxMessageDate {
            get {
                return ResourceManager.GetString("InboxMessageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string InboxMessageDelete {
            get {
                return ResourceManager.GetString("InboxMessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string InboxMessageFrom {
            get {
                return ResourceManager.GetString("InboxMessageFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string InboxMessageOpen {
            get {
                return ResourceManager.GetString("InboxMessageOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string InboxMessageTitle {
            get {
                return ResourceManager.GetString("InboxMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InBox.
        /// </summary>
        public static string InboxTitle {
            get {
                return ResourceManager.GetString("InboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter full description about you.
        /// </summary>
        public static string InstDescError {
            get {
                return ResourceManager.GetString("InstDescError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor Evaluation.
        /// </summary>
        public static string InstEval {
            get {
                return ResourceManager.GetString("InstEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this tutorial not belong to this instructor.
        /// </summary>
        public static string instHasNotThisTut {
            get {
                return ResourceManager.GetString("instHasNotThisTut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select 220 px * 220 px image.
        /// </summary>
        public static string InstImgError {
            get {
                return ResourceManager.GetString("InstImgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Lectures.
        /// </summary>
        public static string InstLecList {
            get {
                return ResourceManager.GetString("InstLecList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor Name.
        /// </summary>
        public static string InstName {
            get {
                return ResourceManager.GetString("InstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string InstProfileUrl {
            get {
                return ResourceManager.GetString("InstProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter job title.
        /// </summary>
        public static string InstTitleError {
            get {
                return ResourceManager.GetString("InstTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tutorials.
        /// </summary>
        public static string InstTut {
            get {
                return ResourceManager.GetString("InstTut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Tutorials.
        /// </summary>
        public static string InstTutList {
            get {
                return ResourceManager.GetString("InstTutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email !.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Lecture Attachment.
        /// </summary>
        public static string LecAttach {
            get {
                return ResourceManager.GetString("LecAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Date.
        /// </summary>
        public static string LecDate {
            get {
                return ResourceManager.GetString("LecDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Description.
        /// </summary>
        public static string LecDesc {
            get {
                return ResourceManager.GetString("LecDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end time of the lecture should be after start time of the lecture.
        /// </summary>
        public static string LecEndBeggerThanLecStart {
            get {
                return ResourceManager.GetString("LecEndBeggerThanLecStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture End Time.
        /// </summary>
        public static string LecEndTime {
            get {
                return ResourceManager.GetString("LecEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are lectures in these times please select another start and end time.
        /// </summary>
        public static string LecsInSameTimeError {
            get {
                return ResourceManager.GetString("LecsInSameTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Start Time.
        /// </summary>
        public static string LecStTime {
            get {
                return ResourceManager.GetString("LecStTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the time of lecture should be begger than current time.
        /// </summary>
        public static string LecTimeError {
            get {
                return ResourceManager.GetString("LecTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Title.
        /// </summary>
        public static string LecTitle {
            get {
                return ResourceManager.GetString("LecTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture.
        /// </summary>
        public static string LecTitleTimeTable {
            get {
                return ResourceManager.GetString("LecTitleTimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectures.
        /// </summary>
        public static string LectureTitle {
            get {
                return ResourceManager.GetString("LectureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial not found for this lecture.
        /// </summary>
        public static string LecTutNotFound {
            get {
                return ResourceManager.GetString("LecTutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Room Url.
        /// </summary>
        public static string LecVirtualUrl {
            get {
                return ResourceManager.GetString("LecVirtualUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of incomming messages.
        /// </summary>
        public static string ListOfInBox {
            get {
                return ResourceManager.GetString("ListOfInBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginBtnVal {
            get {
                return ResourceManager.GetString("LoginBtnVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new student account.
        /// </summary>
        public static string LoginCreateStAccount {
            get {
                return ResourceManager.GetString("LoginCreateStAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Email.
        /// </summary>
        public static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login failed.
        /// </summary>
        public static string LoginFailedMsg {
            get {
                return ResourceManager.GetString("LoginFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget my password.
        /// </summary>
        public static string LoginForgetPass {
            get {
                return ResourceManager.GetString("LoginForgetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string LoginPass {
            get {
                return ResourceManager.GetString("LoginPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuranInstitude - Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        public static string LoginTopHeader {
            get {
                return ResourceManager.GetString("LoginTopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to subscribe.
        /// </summary>
        public static string LoginToSub {
            get {
                return ResourceManager.GetString("LoginToSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogoutTextUrl {
            get {
                return ResourceManager.GetString("LogoutTextUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Request to join tutorial was accepted.
        /// </summary>
        public static string ManagementAccept {
            get {
                return ResourceManager.GetString("ManagementAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string ManagementTitle {
            get {
                return ResourceManager.GetString("ManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the language you want to study in.
        /// </summary>
        public static string MessageRegister {
            get {
                return ResourceManager.GetString("MessageRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Assignment.
        /// </summary>
        public static string MyAssignment {
            get {
                return ResourceManager.GetString("MyAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Evaluate.
        /// </summary>
        public static string MyEvaluate {
            get {
                return ResourceManager.GetString("MyEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tutorials.
        /// </summary>
        public static string MyTutorials {
            get {
                return ResourceManager.GetString("MyTutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in national language.
        /// </summary>
        public static string NameInNational {
            get {
                return ResourceManager.GetString("NameInNational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        public static string NewPassErrorText {
            get {
                return ResourceManager.GetString("NewPassErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the length of new password must more than 6 and less than 50 characters.
        /// </summary>
        public static string NewPassLength {
            get {
                return ResourceManager.GetString("NewPassLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassText {
            get {
                return ResourceManager.GetString("NewPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Attachment uploaded for this Assignment-Homework.
        /// </summary>
        public static string NoPrevAttForAss {
            get {
                return ResourceManager.GetString("NoPrevAttForAss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Attachment for this solution.
        /// </summary>
        public static string NoPrevAttForSol {
            get {
                return ResourceManager.GetString("NoPrevAttForSol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notaccept.
        /// </summary>
        public static string NotAcceptInst {
            get {
                return ResourceManager.GetString("NotAcceptInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is wrong.
        /// </summary>
        public static string OldPassErrorText {
            get {
                return ResourceManager.GetString("OldPassErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassText {
            get {
                return ResourceManager.GetString("OldPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email,full name ,phone number are required.
        /// </summary>
        public static string OtherInstDataError {
            get {
                return ResourceManager.GetString("OtherInstDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for send sms And Your Password is.
        /// </summary>
        public static string PassMsg {
            get {
                return ResourceManager.GetString("PassMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Sent to your phone.
        /// </summary>
        public static string passwordsent {
            get {
                return ResourceManager.GetString("passwordsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone +xxxxx.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone containing country code.
        /// </summary>
        public static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        public static string Poor {
            get {
                return ResourceManager.GetString("Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image 220*220.
        /// </summary>
        public static string ProfileImgLable {
            get {
                return ResourceManager.GetString("ProfileImgLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string RemoveAtt {
            get {
                return ResourceManager.GetString("RemoveAtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Or Subscribed.
        /// </summary>
        public static string RequestedOrSubscribed {
            get {
                return ResourceManager.GetString("RequestedOrSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Resident.
        /// </summary>
        public static string ResidentCountry {
            get {
                return ResourceManager.GetString("ResidentCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satarday.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Attachment.
        /// </summary>
        public static string ShowAtt {
            get {
                return ResourceManager.GetString("ShowAtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Student Assignments.
        /// </summary>
        public static string ShowStudentAssignments {
            get {
                return ResourceManager.GetString("ShowStudentAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tutorial Details.
        /// </summary>
        public static string ShowTutDetails {
            get {
                return ResourceManager.GetString("ShowTutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkan.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Attachments.
        /// </summary>
        public static string SolAttach {
            get {
                return ResourceManager.GetString("SolAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string SolDesc {
            get {
                return ResourceManager.GetString("SolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available tutorials.
        /// </summary>
        public static string StAllTut {
            get {
                return ResourceManager.GetString("StAllTut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your.
        /// </summary>
        public static string StAssociateYourAccount {
            get {
                return ResourceManager.GetString("StAssociateYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string StAssociationForm {
            get {
                return ResourceManager.GetString("StAssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Academic  Certificate Required.
        /// </summary>
        public static string StCertRequired {
            get {
                return ResourceManager.GetString("StCertRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Registeration.
        /// </summary>
        public static string StCompleteRegister {
            get {
                return ResourceManager.GetString("StCompleteRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create - Edit Student Account.
        /// </summary>
        public static string StCreateAccountTitle {
            get {
                return ResourceManager.GetString("StCreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Degree.
        /// </summary>
        public static string StDegree {
            get {
                return ResourceManager.GetString("StDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string StExLoginAccount {
            get {
                return ResourceManager.GetString("StExLoginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebook login.
        /// </summary>
        public static string StExLoginBtnFace {
            get {
                return ResourceManager.GetString("StExLoginBtnFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using facebook account.
        /// </summary>
        public static string StExLoginUsing {
            get {
                return ResourceManager.GetString("StExLoginUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a phone number for this site below and click the Register button to finish logging in..
        /// </summary>
        public static string StFinishLoginMsg {
            get {
                return ResourceManager.GetString("StFinishLoginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string StLoginFailure {
            get {
                return ResourceManager.GetString("StLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions of registration.
        /// </summary>
        public static string StRegReq1 {
            get {
                return ResourceManager.GetString("StRegReq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9- Attending the introductory session on the study plan and passing the personal interview aimed at identifying the student’s capabilities, determining his level, and guiding him to the appropriate study plan.
        /// </summary>
        public static string StRegReq10 {
            get {
                return ResourceManager.GetString("StRegReq10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10- Buying the educational curriculum, which is the printed or electronic book of Al Qaida Al Noorania.
        /// </summary>
        public static string StRegReq11 {
            get {
                return ResourceManager.GetString("StRegReq11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- The applicant must be 7 years old or more.
        /// </summary>
        public static string StRegReq2 {
            get {
                return ResourceManager.GetString("StRegReq2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2- Memorizing the Arabic letters before starting the course..
        /// </summary>
        public static string StRegReq3 {
            get {
                return ResourceManager.GetString("StRegReq3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3- Seriousness and commitment to attend until the end of the course..
        /// </summary>
        public static string StRegReq4 {
            get {
                return ResourceManager.GetString("StRegReq4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4- That the student is good at using the computer, or there is someone who helps him to do so with the student.
        /// </summary>
        public static string StRegReq5 {
            get {
                return ResourceManager.GetString("StRegReq5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5- That the student adhere to public morals and etiquette for learning the Qur’an.
        /// </summary>
        public static string StRegReq6 {
            get {
                return ResourceManager.GetString("StRegReq6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6- Parents are obligated to follow the child during the educational session.
        /// </summary>
        public static string StRegReq7 {
            get {
                return ResourceManager.GetString("StRegReq7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7- Fill out the registration form, write the required information accurately, and make sure to read the terms and conditions.
        /// </summary>
        public static string StRegReq8 {
            get {
                return ResourceManager.GetString("StRegReq8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8- Register on the platform using e-mail and phone number for verification.
        /// </summary>
        public static string StRegReq9 {
            get {
                return ResourceManager.GetString("StRegReq9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string StScore {
            get {
                return ResourceManager.GetString("StScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        public static string StSuccessExternalAuth {
            get {
                return ResourceManager.GetString("StSuccessExternalAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Academic  Certificate.
        /// </summary>
        public static string StudentCert {
            get {
                return ResourceManager.GetString("StudentCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certify Student.
        /// </summary>
        public static string StudentCertify {
            get {
                return ResourceManager.GetString("StudentCertify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students List.
        /// </summary>
        public static string StudentsList {
            get {
                return ResourceManager.GetString("StudentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string StUnsuccessfullLgin {
            get {
                return ResourceManager.GetString("StUnsuccessfullLgin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With your Account.
        /// </summary>
        public static string StWithMyAccount {
            get {
                return ResourceManager.GetString("StWithMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscribedStudents.
        /// </summary>
        public static string SubStudents {
            get {
                return ResourceManager.GetString("SubStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have technical problems during the session.
        /// </summary>
        public static string TechProblemInTutorial {
            get {
                return ResourceManager.GetString("TechProblemInTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thur {
            get {
                return ResourceManager.GetString("Thur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Table.
        /// </summary>
        public static string TimeTable {
            get {
                return ResourceManager.GetString("TimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuseday.
        /// </summary>
        public static string Tus {
            get {
                return ResourceManager.GetString("Tus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorail assigned to you.
        /// </summary>
        public static string TutAssignToInst {
            get {
                return ResourceManager.GetString("TutAssignToInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial Close Date.
        /// </summary>
        public static string TutCloseDate {
            get {
                return ResourceManager.GetString("TutCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Of Lictures.
        /// </summary>
        public static string TutCount {
            get {
                return ResourceManager.GetString("TutCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial Details.
        /// </summary>
        public static string TutDetails {
            get {
                return ResourceManager.GetString("TutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        public static string TutInstName {
            get {
                return ResourceManager.GetString("TutInstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of Tutorial.
        /// </summary>
        public static string TutLang {
            get {
                return ResourceManager.GetString("TutLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial Lectures.
        /// </summary>
        public static string TutLectures {
            get {
                return ResourceManager.GetString("TutLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial Date.
        /// </summary>
        public static string TutOpenDate {
            get {
                return ResourceManager.GetString("TutOpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial Title.
        /// </summary>
        public static string TutorialTitle {
            get {
                return ResourceManager.GetString("TutorialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuor UserName is.
        /// </summary>
        public static string UserNameMsg {
            get {
                return ResourceManager.GetString("UserNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Verfication.
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        public static string VGood {
            get {
                return ResourceManager.GetString("VGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Video Url.
        /// </summary>
        public static string VideoUrl {
            get {
                return ResourceManager.GetString("VideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
